#!/bin/bash

	awk 'BEGIN{
		s="HelloWorld"; s=s s s s s s s s s s s s s s s s s s;
        k=79
		for (colnum = 0; colnum<=k; colnum++) {
			r = 255-(colnum*255/k);
			g = (colnum*510/k);
			b = (colnum*255/k);
			if (g>255) g = 510-g;
			printf "\033[48;2;%d;%d;%dm", r,g,b;
			printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
			printf "%s\033[0m", substr(s,colnum+1,1);
		}
		printf "\n";
	}'


